version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=main
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    # Render handles the port assignment

    # This ensures that db is available when web starts up, but it doesn’t guarantee that the database is ready.
    # For full readiness control, consider using a health check script.
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: